CC = gcc
CFLAGS = -O2 -std=gnu11 -g -Wall -fsanitize=address
INCLUDE = -I../include

hash_demo1: hash_demo1.c
	$(CC) $(CFLAGS) $(INCLUDE) hash_demo1.c -o hash_demo1

hash_demo2: hash_demo2.c
	$(CC) $(CFLAGS) $(INCLUDE) hash_demo2.c -o hash_demo2

hash_demo3: hash_demo3.c
	$(CC) $(CFLAGS) $(INCLUDE) hash_demo3.c -o hash_demo3

hash_demo4: hash_demo4.c
	$(CC) $(CFLAGS) $(INCLUDE) hash_demo4.c -o hash_demo4 -lm

hash_demo5: hash_demo5.c
	$(CC) $(CFLAGS) $(INCLUDE) hash_demo5.c -o hash_demo5

hash_demo6: hash_demo6.c
	$(CC) $(CFLAGS) $(INCLUDE) hash_demo6.c -o hash_demo6

hash_demo7: hash_demo7.c
	$(CC) $(CFLAGS) $(INCLUDE) hash_demo7.c -o hash_demo7

hash_demo8: hash_demo8.c
	$(CC) $(CFLAGS) $(INCLUDE) hash_demo8.c -o hash_demo8

phash_demo1: phash_demo1.c
	$(CC) $(CFLAGS) $(INCLUDE) phash_demo1.c -o phash_demo1 -lpthread

chan_demo1: chan_demo1.c
	$(CC) $(CFLAGS) $(INCLUDE) chan_demo1.c -o chan_demo1 -lpthread

chan_demo2: chan_demo2.c
	$(CC) $(CFLAGS) $(INCLUDE) chan_demo2.c -o chan_demo2 -lpthread -fopenmp

chan_demo3: chan_demo3.c
	$(CC) $(CFLAGS) $(INCLUDE) chan_demo3.c -o chan_demo3 -lpthread -fopenmp

chan_demo4: chan_demo4.c
	$(CC) $(CFLAGS) $(INCLUDE) chan_demo4.c -o chan_demo4 -lpthread -lm -fopenmp

linked_list_demo1: linked_list_demo1.c
	$(CC) $(CFLAGS) $(INCLUDE) linked_list_demo1.c -o linked_list_demo1 -lm

linked_list_demo2: linked_list_demo2.c
	$(CC) $(CFLAGS) $(INCLUDE) linked_list_demo2.c -o linked_list_demo2

linked_list_demo3: linked_list_demo3.c
	$(CC) $(CFLAGS) $(INCLUDE) linked_list_demo3.c -o linked_list_demo3

comp_demo: comp_demo.c
	$(CC) $(CFLAGS) $(INCLUDE) comp_demo.c -o comp_demo

array_demo1: array_demo1.c
	$(CC) $(CFLAGS) $(INCLUDE) array_demo1.c -o array_demo1

array_demo2: array_demo2.c
	$(CC) $(CFLAGS) $(INCLUDE) array_demo2.c -o array_demo2

array_demo3: array_demo3.c
	$(CC) $(CFLAGS) $(INCLUDE) array_demo3.c -o array_demo3

array_demo4: array_demo4.c
	$(CC) $(CFLAGS) $(INCLUDE) array_demo4.c -o array_demo4

array_demo5: array_demo5.c
	$(CC) $(CFLAGS) $(INCLUDE) array_demo5.c -o array_demo5

array_demo6: array_demo6.c
	$(CC) $(CFLAGS) $(INCLUDE) array_demo6.c -o array_demo6

array_demo7: array_demo7.c
	$(CC) $(CFLAGS) $(INCLUDE) array_demo7.c -o array_demo7

array_demo8: array_demo8.c
	$(CC) $(CFLAGS) $(INCLUDE) array_demo8.c -o array_demo8 -lm

array_demo9: array_demo9.c
	$(CC) $(CFLAGS) $(INCLUDE) array_demo9.c -o array_demo9

array_demo10: array_demo10.c
	$(CC) $(CFLAGS) $(INCLUDE) array_demo10.c -o array_demo10

array_demo11: array_demo11.c
	$(CC) $(CFLAGS) $(INCLUDE) array_demo11.c -o array_demo11

array_demo12: array_demo12.c
	$(CC) $(CFLAGS) $(INCLUDE) array_demo12.c -o array_demo12

array_demo13: array_demo13.c
	$(CC) $(CFLAGS) $(INCLUDE) array_demo13.c -o array_demo13

array_demo14: array_demo14.c
	$(CC) $(CFLAGS) $(INCLUDE) array_demo14.c -o array_demo14

array_demo15: array_demo15.c
	$(CC) $(CFLAGS) $(INCLUDE) array_demo15.c -o array_demo15

tree_demo1: tree_demo1.c
	$(CC) $(CFLAGS) $(INCLUDE) tree_demo1.c -o tree_demo1

tree_demo2: tree_demo2.c
	$(CC) $(CFLAGS) $(INCLUDE) tree_demo2.c -o tree_demo2

tree_demo3: tree_demo3.c
	$(CC) $(CFLAGS) $(INCLUDE) tree_demo3.c -o tree_demo3

tree_demo4: tree_demo4.c
	$(CC) $(CFLAGS) $(INCLUDE) tree_demo4.c -o tree_demo4

tree_demo5: tree_demo5.c
	$(CC) $(CFLAGS) $(INCLUDE) tree_demo5.c -o tree_demo5

tree_demo6: tree_demo6.c
	$(CC) $(CFLAGS) $(INCLUDE) tree_demo6.c -o tree_demo6

tree_demo7: tree_demo7.c
	$(CC) $(CFLAGS) $(INCLUDE) tree_demo7.c -o tree_demo7

tree_demo8: tree_demo8.c
	$(CC) $(CFLAGS) $(INCLUDE) tree_demo8.c -o tree_demo8

tree_demo9: tree_demo9.c
	$(CC) $(CFLAGS) $(INCLUDE) tree_demo9.c -o tree_demo9

tree_demo10: tree_demo10.c
	$(CC) $(CFLAGS) $(INCLUDE) tree_demo10.c -o tree_demo10

tree_demo11: tree_demo11.c
	$(CC) $(CFLAGS) $(INCLUDE) tree_demo11.c -o tree_demo11

tree_array_demo: tree_array_demo.c
	$(CC) $(CFLAGS) $(INCLUDE) tree_array_demo.c -o tree_array_demo

chan2_demo1: chan2_demo1.c
	$(CC) $(CFLAGS) $(INCLUDE) chan2_demo1.c -o chan2_demo1

chan2_demo2: chan2_demo2.c
	$(CC) $(CFLAGS) $(INCLUDE) chan2_demo2.c -o chan2_demo2 -fopenmp

chan2_demo3: chan2_demo3.c
	$(CC) $(CFLAGS) $(INCLUDE) chan2_demo3.c -o chan2_demo3 -fopenmp

chan2_demo4: chan2_demo4.c
	$(CC) $(CFLAGS) $(INCLUDE) chan2_demo4.c -o chan2_demo4 -fopenmp -lm


clean:
	rm -rf array_demo1
	rm -rf array_demo2
	rm -rf array_demo3
	rm -rf array_demo4
	rm -rf array_demo5
	rm -rf array_demo6
	rm -rf array_demo7
	rm -rf array_demo8
	rm -rf array_demo9
	rm -rf array_demo10
	rm -rf array_demo11
	rm -rf array_demo12
	rm -rf array_demo13
	rm -rf array_demo14
	rm -rf array_demo15
	rm -rf hash_demo1
	rm -rf hash_demo2
	rm -rf hash_demo3
	rm -rf hash_demo4
	rm -rf hash_demo5
	rm -rf hash_demo6
	rm -rf hash_demo7
	rm -rf hash_demo8
	rm -rf phash_demo1
	rm -rf chan_demo1
	rm -rf chan_demo2
	rm -rf chan_demo3
	rm -rf chan_demo4
	rm -rf linked_list_demo1
	rm -rf linked_list_demo2
	rm -rf linked_list_demo3
	rm -rf tree_demo1
	rm -rf tree_demo2
	rm -rf tree_demo3
	rm -rf tree_demo4
	rm -rf tree_demo5
	rm -rf tree_demo6
	rm -rf tree_demo7
	rm -rf tree_demo8
	rm -rf tree_demo9
	rm -rf tree_demo10
	rm -rf tree_demo11
	rm -rf tree_array_demo
	rm -rf chan2_demo1
	rm -rf chan2_demo2
	rm -rf chan2_demo3
	rm -rf chan2_demo4
	rm -rf *~

