CC = gcc
CFLAGS = -O2 -std=gnu11 -g
INCLUDE = -I../include

hash_demo1: hash_demo1.c
	$(CC) $(CFLAGS) $(INCLUDE) hash_demo1.c -o hash_demo1

hash_demo2: hash_demo2.c
	$(CC) $(CFLAGS) $(INCLUDE) hash_demo2.c -o hash_demo2

hash_demo3: hash_demo3.c
	$(CC) $(CFLAGS) $(INCLUDE) hash_demo3.c -o hash_demo3

linked_list_demo: linked_list_demo.c
	$(CC) $(CFLAGS) $(INCLUDE) linked_list_demo.c -o linked_list_demo -lm

linked_list_demo2: linked_list_demo2.c
	$(CC) $(CFLAGS) $(INCLUDE) linked_list_demo2.c -o linked_list_demo2

comp_demo: comp_demo.c
	$(CC) $(CFLAGS) $(INCLUDE) comp_demo.c -o comp_demo

array_demo1: array_demo1.c
	$(CC) $(CFLAGS) $(INCLUDE) array_demo1.c -o array_demo1

array_demo2: array_demo2.c
	$(CC) $(CFLAGS) $(INCLUDE) array_demo2.c -o array_demo2

array_demo3: array_demo3.c
	$(CC) $(CFLAGS) $(INCLUDE) array_demo3.c -o array_demo3

array_demo4: array_demo4.c
	$(CC) $(CFLAGS) $(INCLUDE) array_demo4.c -o array_demo4

array_demo5: array_demo5.c
	$(CC) $(CFLAGS) $(INCLUDE) array_demo5.c -o array_demo5

array_demo6: array_demo6.c
	$(CC) $(CFLAGS) $(INCLUDE) array_demo6.c -o array_demo6

array_demo7: array_demo7.c
	$(CC) $(CFLAGS) $(INCLUDE) array_demo7.c -o array_demo7

array_demo8: array_demo8.c
	$(CC) $(CFLAGS) $(INCLUDE) array_demo8.c -o array_demo8 -lm

array_demo9: array_demo9.c
	$(CC) $(CFLAGS) $(INCLUDE) array_demo9.c -o array_demo9

tree_demo1: tree_demo1.c
	$(CC) $(CFLAGS) $(INCLUDE) tree_demo1.c -o tree_demo1

tree_demo2: tree_demo2.c
	$(CC) $(CFLAGS) $(INCLUDE) tree_demo2.c -o tree_demo2

tree_demo3: tree_demo3.c
	$(CC) $(CFLAGS) $(INCLUDE) tree_demo3.c -o tree_demo3

tree_demo4: tree_demo4.c
	$(CC) $(CFLAGS) $(INCLUDE) tree_demo4.c -o tree_demo4

tree_demo5: tree_demo5.c
	$(CC) $(CFLAGS) $(INCLUDE) tree_demo5.c -o tree_demo5

tree_demo6: tree_demo6.c
	$(CC) $(CFLAGS) $(INCLUDE) tree_demo6.c -o tree_demo6

tree_demo7: tree_demo7.c
	$(CC) $(CFLAGS) $(INCLUDE) tree_demo7.c -o tree_demo7

tree_demo8: tree_demo8.c
	$(CC) $(CFLAGS) $(INCLUDE) tree_demo8.c -o tree_demo8

tree_demo9: tree_demo9.c
	$(CC) $(CFLAGS) $(INCLUDE) tree_demo9.c -o tree_demo9

tree_demo10: tree_demo10.c
	$(CC) $(CFLAGS) $(INCLUDE) tree_demo10.c -o tree_demo10
