CC = gcc
CFLAGS = -O2 -std=gnu11
INCLUDE = -I../include

linked_list_demo: linked_list_demo.c
    $(CC) $(CFLAGS) $(INCLUDE) linked_list_demo.c -o linked_list_demo
    
comp_demo: comp_demo.c
    $(CC) $(CFLAGS) $(INCLUDE) comp_demo.c -o comp_demo
    
    